[network]
host = 127.0.0.1
port = 8888
backlog = 128

[mysql]
host = localhost
port = 3306
user = test
password = 123456
database = cloud_drive_demo
charset = utf8mb4
pool_size = 4

[storage]
root_dir = data/files
transfer_temp_dir = data/.upload


[thread_pool]
thread_num = 4
queue_capacity = 1024

[log]
log_level = info
log_file = logs/server.log
